"""p0_canonical_entity_spine

Revision ID: 0d3d077fde25
Revises: c992ddc1abfa
Create Date: 2026-07-28 18:16:13.344846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d3d077fde25'
down_revision: Union[str, Sequence[str], None] = 'c992ddc1abfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=300), nullable=True),
    sa.Column('jurisdiction_code', sa.String(length=10), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('input_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('canonical_key', sa.String(length=200), nullable=True),
    sa.Column('pesticide_product_id', sa.Integer(), nullable=True),
    sa.Column('unit_of_sale', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pesticide_product_id'], ['pesticide_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('input_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_input_products_canonical_key'), ['canonical_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_input_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_input_products_pesticide_product_id'), ['pesticide_product_id'], unique=False)

    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('party_type', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('jurisdiction_code', sa.String(length=10), nullable=True),
    sa.Column('external_ids', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parties_organization_id'), ['organization_id'], unique=False)

    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('boundary_geojson', sa.Text(), nullable=True),
    sa.Column('centroid_lat', sa.Float(), nullable=True),
    sa.Column('centroid_lon', sa.Float(), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('display_area', sa.Float(), nullable=True),
    sa.Column('display_area_unit', sa.String(length=10), nullable=True),
    sa.Column('irrigation_type', sa.String(length=60), nullable=True),
    sa.Column('water_source', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fields_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fields_organization_id'), ['organization_id'], unique=False)

    op.create_table('land_parcels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('parcel_identifier', sa.String(length=120), nullable=True),
    sa.Column('registry_name', sa.String(length=160), nullable=True),
    sa.Column('county', sa.String(length=120), nullable=True),
    sa.Column('jurisdiction_code', sa.String(length=10), nullable=True),
    sa.Column('boundary_geojson', sa.Text(), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('land_parcels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_land_parcels_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_land_parcels_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_land_parcels_parcel_identifier'), ['parcel_identifier'], unique=False)

    op.create_table('party_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('party_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_party_roles_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_party_roles_party_id'), ['party_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_party_roles_role'), ['role'], unique=False)

    op.create_table('crop_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('variety_name', sa.String(length=160), nullable=True),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('season_label', sa.String(length=60), nullable=True),
    sa.Column('planting_date', sa.Date(), nullable=True),
    sa.Column('expected_harvest_start', sa.Date(), nullable=True),
    sa.Column('expected_harvest_end', sa.Date(), nullable=True),
    sa.Column('actual_harvest_start', sa.Date(), nullable=True),
    sa.Column('actual_harvest_end', sa.Date(), nullable=True),
    sa.Column('planted_area_m2', sa.Float(), nullable=True),
    sa.Column('display_area', sa.Float(), nullable=True),
    sa.Column('display_area_unit', sa.String(length=10), nullable=True),
    sa.Column('target_market', sa.String(length=60), nullable=True),
    sa.Column('target_grade', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crop_cycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crop_cycles_crop'), ['crop'], unique=False)
        batch_op.create_index(batch_op.f('ix_crop_cycles_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crop_cycles_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crop_cycles_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crop_cycles_season_year'), ['season_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_crop_cycles_status'), ['status'], unique=False)

    op.create_table('field_parcel_overlaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('land_parcel_id', sa.Integer(), nullable=False),
    sa.Column('overlap_area_m2', sa.Float(), nullable=True),
    sa.Column('determination_method', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['land_parcel_id'], ['land_parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_parcel_overlaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_field_parcel_overlaps_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_parcel_overlaps_land_parcel_id'), ['land_parcel_id'], unique=False)
        batch_op.create_index('uq_field_parcel_overlap', ['field_id', 'land_parcel_id'], unique=True)

    op.create_table('tenure_rights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('land_parcel_id', sa.Integer(), nullable=False),
    sa.Column('holder_party_id', sa.Integer(), nullable=True),
    sa.Column('tenure_type', sa.String(length=30), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('annual_cost_amount', sa.Float(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['holder_party_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['land_parcel_id'], ['land_parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenure_rights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenure_rights_holder_party_id'), ['holder_party_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenure_rights_land_parcel_id'), ['land_parcel_id'], unique=False)

    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('crop_cycle_id', sa.Integer(), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('operation_type', sa.String(length=40), nullable=False),
    sa.Column('planned_on', sa.Date(), nullable=True),
    sa.Column('performed_on', sa.Date(), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('display_area', sa.Float(), nullable=True),
    sa.Column('display_area_unit', sa.String(length=10), nullable=True),
    sa.Column('cost_amount', sa.Float(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('performed_by', sa.String(length=120), nullable=True),
    sa.Column('performed_by_party_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['performed_by_party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operations_block_id'), ['block_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_crop_cycle_id'), ['crop_cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_performed_on'), ['performed_on'], unique=False)

    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_blocks_field_id'), ['field_id'], unique=False)
        batch_op.create_foreign_key('fk_blocks_field_id', 'fields', ['field_id'], ['id'])

    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('currency_code', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('jurisdiction_code', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_farms_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key('fk_farms_organization_id', 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('input_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crop_cycle_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_input_plans_crop_cycle_id'), ['crop_cycle_id'], unique=False)
        batch_op.create_foreign_key('fk_input_plans_crop_cycle_id', 'crop_cycles', ['crop_cycle_id'], ['id'])

    with op.batch_alter_table('planned_sprays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crop_cycle_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('field_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_planned_sprays_crop_cycle_id'), ['crop_cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_planned_sprays_field_id'), ['field_id'], unique=False)
        batch_op.create_foreign_key('fk_planned_sprays_field_id', 'fields', ['field_id'], ['id'])
        batch_op.create_foreign_key('fk_planned_sprays_crop_cycle_id', 'crop_cycles', ['crop_cycle_id'], ['id'])

    with op.batch_alter_table('scout_observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crop_cycle_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('field_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_scout_observations_crop_cycle_id'), ['crop_cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scout_observations_field_id'), ['field_id'], unique=False)
        batch_op.create_foreign_key('fk_scout_observations_crop_cycle_id', 'crop_cycles', ['crop_cycle_id'], ['id'])
        batch_op.create_foreign_key('fk_scout_observations_field_id', 'fields', ['field_id'], ['id'])

    with op.batch_alter_table('scouting_samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crop_cycle_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_scouting_samples_crop_cycle_id'), ['crop_cycle_id'], unique=False)
        batch_op.create_foreign_key('fk_scouting_samples_crop_cycle_id', 'crop_cycles', ['crop_cycle_id'], ['id'])

    with op.batch_alter_table('spray_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crop_cycle_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('field_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('operation_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_spray_events_crop_cycle_id'), ['crop_cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spray_events_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spray_events_operation_id'), ['operation_id'], unique=False)
        batch_op.create_foreign_key('fk_spray_events_operation_id', 'operations', ['operation_id'], ['id'])
        batch_op.create_foreign_key('fk_spray_events_field_id', 'fields', ['field_id'], ['id'])
        batch_op.create_foreign_key('fk_spray_events_crop_cycle_id', 'crop_cycles', ['crop_cycle_id'], ['id'])

    with op.batch_alter_table('weather_observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_weather_observations_field_id'), ['field_id'], unique=False)
        batch_op.create_foreign_key('fk_weather_observations_field_id', 'fields', ['field_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Batch mode recreates each table from the remaining columns, so dropping a link
    column removes its foreign key with it — no explicit `drop_constraint`. This
    follows `509a5fb37e3b` and `fd3e65674140`, which hit the same thing: autogenerate
    emits `drop_constraint(None, ...)` and SQLite cannot resolve an unnamed constraint,
    so the chain failed to reach base.
    """
    with op.batch_alter_table('weather_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_observations_field_id'))
        batch_op.drop_column('field_id')

    with op.batch_alter_table('spray_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spray_events_operation_id'))
        batch_op.drop_index(batch_op.f('ix_spray_events_field_id'))
        batch_op.drop_index(batch_op.f('ix_spray_events_crop_cycle_id'))
        batch_op.drop_column('operation_id')
        batch_op.drop_column('field_id')
        batch_op.drop_column('crop_cycle_id')

    with op.batch_alter_table('scouting_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scouting_samples_crop_cycle_id'))
        batch_op.drop_column('crop_cycle_id')

    with op.batch_alter_table('scout_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scout_observations_field_id'))
        batch_op.drop_index(batch_op.f('ix_scout_observations_crop_cycle_id'))
        batch_op.drop_column('field_id')
        batch_op.drop_column('crop_cycle_id')

    with op.batch_alter_table('planned_sprays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planned_sprays_field_id'))
        batch_op.drop_index(batch_op.f('ix_planned_sprays_crop_cycle_id'))
        batch_op.drop_column('field_id')
        batch_op.drop_column('crop_cycle_id')

    with op.batch_alter_table('input_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_input_plans_crop_cycle_id'))
        batch_op.drop_column('crop_cycle_id')

    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farms_organization_id'))
        batch_op.drop_column('jurisdiction_code')
        batch_op.drop_column('timezone')
        batch_op.drop_column('currency_code')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocks_field_id'))
        batch_op.drop_column('field_id')

    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operations_performed_on'))
        batch_op.drop_index(batch_op.f('ix_operations_operation_type'))
        batch_op.drop_index(batch_op.f('ix_operations_field_id'))
        batch_op.drop_index(batch_op.f('ix_operations_farm_id'))
        batch_op.drop_index(batch_op.f('ix_operations_crop_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_operations_block_id'))

    op.drop_table('operations')
    with op.batch_alter_table('tenure_rights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenure_rights_land_parcel_id'))
        batch_op.drop_index(batch_op.f('ix_tenure_rights_holder_party_id'))

    op.drop_table('tenure_rights')
    with op.batch_alter_table('field_parcel_overlaps', schema=None) as batch_op:
        batch_op.drop_index('uq_field_parcel_overlap')
        batch_op.drop_index(batch_op.f('ix_field_parcel_overlaps_land_parcel_id'))
        batch_op.drop_index(batch_op.f('ix_field_parcel_overlaps_field_id'))

    op.drop_table('field_parcel_overlaps')
    with op.batch_alter_table('crop_cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crop_cycles_status'))
        batch_op.drop_index(batch_op.f('ix_crop_cycles_season_year'))
        batch_op.drop_index(batch_op.f('ix_crop_cycles_organization_id'))
        batch_op.drop_index(batch_op.f('ix_crop_cycles_field_id'))
        batch_op.drop_index(batch_op.f('ix_crop_cycles_farm_id'))
        batch_op.drop_index(batch_op.f('ix_crop_cycles_crop'))

    op.drop_table('crop_cycles')
    with op.batch_alter_table('party_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_party_roles_role'))
        batch_op.drop_index(batch_op.f('ix_party_roles_party_id'))
        batch_op.drop_index(batch_op.f('ix_party_roles_organization_id'))

    op.drop_table('party_roles')
    with op.batch_alter_table('land_parcels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_land_parcels_parcel_identifier'))
        batch_op.drop_index(batch_op.f('ix_land_parcels_organization_id'))
        batch_op.drop_index(batch_op.f('ix_land_parcels_farm_id'))

    op.drop_table('land_parcels')
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fields_organization_id'))
        batch_op.drop_index(batch_op.f('ix_fields_farm_id'))

    op.drop_table('fields')
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parties_organization_id'))

    op.drop_table('parties')
    with op.batch_alter_table('input_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_input_products_pesticide_product_id'))
        batch_op.drop_index(batch_op.f('ix_input_products_category'))
        batch_op.drop_index(batch_op.f('ix_input_products_canonical_key'))

    op.drop_table('input_products')
    op.drop_table('organizations')
    # ### end Alembic commands ###
