"""align residue_reference_records.created_at with the model

Revision ID: 1e96526d950e
Revises: f356b91d9d1f
Create Date: 2026-08-12 21:15:53.838624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e96526d950e'
down_revision: Union[str, Sequence[str], None] = 'f356b91d9d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Make `created_at` NOT NULL, matching the model that always said so.

    `3e83278911f2` hand-wrote this table and used `nullable=True`, while
    `models.ResidueReferenceRecord.created_at` is `Mapped[datetime]` — non-optional,
    with a Python-side default. No row has ever been NULL; only the schema disagreed
    with the model about whether one could be.

    Found by the migration-drift check the CI workflow added, which was the first
    thing in this repo to compare a MIGRATION-BUILT database against the models
    (the test suite runs on `create_all`, which is built from the models and so can
    never see this class of divergence).
    """
    with op.batch_alter_table('residue_reference_records', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residue_reference_records', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
