"""baseline schema

Revision ID: 32a030ba8bc4
Revises: 
Create Date: 2026-07-18 22:36:35.410104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32a030ba8bc4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_judgments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('planned_spray_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('input_digest', sa.String(length=64), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('abstained', sa.Boolean(), nullable=False),
    sa.Column('abstain_reason', sa.Text(), nullable=True),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('crop_type', sa.String(length=100), nullable=False),
    sa.Column('greenhouse_area', sa.Float(), nullable=True),
    sa.Column('area_unit', sa.String(length=10), nullable=True),
    sa.Column('planting_date', sa.Date(), nullable=True),
    sa.Column('expected_harvest_date', sa.Date(), nullable=True),
    sa.Column('advisor_involved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pilot_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('planned_spray_id', sa.Integer(), nullable=True),
    sa.Column('entry_source', sa.String(length=40), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pilot_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('person_type', sa.String(length=40), nullable=False),
    sa.Column('crop', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('current_records_method', sa.String(length=40), nullable=True),
    sa.Column('biggest_pain', sa.String(length=40), nullable=True),
    sa.Column('would_use_real_data', sa.String(length=10), nullable=True),
    sa.Column('would_pay', sa.String(length=10), nullable=True),
    sa.Column('requested_pilot', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('input_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requested_by', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('financing_requested', sa.Boolean(), nullable=False),
    sa.Column('financing_requested_by', sa.String(length=120), nullable=True),
    sa.Column('financing_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.String(length=120), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('selected_quote_id', sa.Integer(), nullable=True),
    sa.Column('selected_by', sa.String(length=120), nullable=True),
    sa.Column('selection_reason', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('input_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_input_plans_farm_id'), ['farm_id'], unique=False)

    op.create_table('pca_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('target_pest_or_disease', sa.String(length=200), nullable=False),
    sa.Column('min_severity_to_treat', sa.Integer(), nullable=False),
    sa.Column('entered_by', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pilot_import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('source_label', sa.String(length=200), nullable=False),
    sa.Column('imported_by', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('record_type', sa.String(length=40), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('ai_judgment_id', sa.Integer(), nullable=True),
    sa.Column('spray_event_count', sa.Integer(), nullable=False),
    sa.Column('scouting_observation_count', sa.Integer(), nullable=False),
    sa.Column('planned_spray_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ai_judgment_id'], ['ai_judgments.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('next_action', sa.String(length=120), nullable=False),
    sa.Column('recommendation_text', sa.Text(), nullable=False),
    sa.Column('agronomist_status', sa.String(length=20), nullable=False),
    sa.Column('agronomist_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spray_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('cadence_days', sa.Integer(), nullable=True),
    sa.Column('season_spray_count', sa.Integer(), nullable=True),
    sa.Column('baseline_period_start', sa.Date(), nullable=True),
    sa.Column('baseline_period_end', sa.Date(), nullable=True),
    sa.Column('calendar_program', sa.String(length=40), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('declared_by', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('input_plan_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_plan_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['input_plan_id'], ['input_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('input_plan_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_input_plan_events_input_plan_id'), ['input_plan_id'], unique=False)

    op.create_table('scout_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('crop_stage', sa.String(length=100), nullable=True),
    sa.Column('visible_issue', sa.String(length=200), nullable=True),
    sa.Column('severity_1_to_5', sa.Integer(), nullable=True),
    sa.Column('image_url_optional', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('external_record_id', sa.String(length=120), nullable=True),
    sa.Column('field_block', sa.String(length=120), nullable=True),
    sa.Column('severity_scale', sa.String(length=40), nullable=True),
    sa.Column('count_value', sa.Float(), nullable=True),
    sa.Column('observer', sa.String(length=120), nullable=True),
    sa.Column('source_system', sa.String(length=120), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('pilot_import_batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['pilot_import_batch_id'], ['pilot_import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spray_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('active_ingredient', sa.String(length=200), nullable=True),
    sa.Column('moa_group', sa.String(length=40), nullable=True),
    sa.Column('pesticide_class', sa.String(length=100), nullable=True),
    sa.Column('target_pest_or_disease', sa.String(length=200), nullable=True),
    sa.Column('dose', sa.String(length=100), nullable=True),
    sa.Column('rate_amount', sa.Float(), nullable=True),
    sa.Column('rate_unit', sa.String(length=40), nullable=True),
    sa.Column('treated_acres', sa.Float(), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('pre_harvest_interval_days', sa.Integer(), nullable=True),
    sa.Column('re_entry_interval_hours', sa.Integer(), nullable=True),
    sa.Column('field_block', sa.String(length=120), nullable=True),
    sa.Column('external_record_id', sa.String(length=120), nullable=True),
    sa.Column('source_system', sa.String(length=120), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('pilot_import_batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['pilot_import_batch_id'], ['pilot_import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_plan_id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('supplier_contact', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('delivery_cost', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('payment_terms_cash', sa.String(length=200), nullable=True),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('verification', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('entered_by', sa.String(length=120), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['input_plan_id'], ['input_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_quotes_input_plan_id'), ['input_plan_id'], unique=False)

    op.create_table('financing_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_quote_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=200), nullable=False),
    sa.Column('requested_amount', sa.Float(), nullable=False),
    sa.Column('down_payment', sa.Float(), nullable=False),
    sa.Column('financed_amount', sa.Float(), nullable=False),
    sa.Column('total_repayment', sa.Float(), nullable=False),
    sa.Column('fees_total', sa.Float(), nullable=False),
    sa.Column('schedule_summary', sa.String(length=300), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('required_documents', sa.Text(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.String(length=120), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('entered_by', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_quote_id'], ['supplier_quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financing_offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financing_offers_supplier_quote_id'), ['supplier_quote_id'], unique=False)

    op.create_table('planned_sprays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('intended_date', sa.Date(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('active_ingredient', sa.String(length=200), nullable=True),
    sa.Column('target_pest_or_disease', sa.String(length=200), nullable=True),
    sa.Column('pre_harvest_interval_days', sa.Integer(), nullable=True),
    sa.Column('re_entry_interval_hours', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('external_record_id', sa.String(length=120), nullable=True),
    sa.Column('field_block', sa.String(length=120), nullable=True),
    sa.Column('crop', sa.String(length=100), nullable=True),
    sa.Column('treated_acres', sa.Float(), nullable=True),
    sa.Column('epa_reg_no', sa.String(length=60), nullable=True),
    sa.Column('moa_group', sa.String(length=40), nullable=True),
    sa.Column('rate_amount', sa.Float(), nullable=True),
    sa.Column('rate_unit', sa.String(length=40), nullable=True),
    sa.Column('recommendation_author', sa.String(length=120), nullable=True),
    sa.Column('source_system', sa.String(length=120), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pilot_import_batch_id', sa.Integer(), nullable=True),
    sa.Column('values_source', sa.String(length=30), nullable=False),
    sa.Column('values_entered_by', sa.String(length=120), nullable=True),
    sa.Column('decision_outcome', sa.String(length=30), nullable=False),
    sa.Column('decision_severity', sa.String(length=20), nullable=False),
    sa.Column('decision_confidence', sa.String(length=20), nullable=False),
    sa.Column('decision_authority', sa.String(length=30), nullable=False),
    sa.Column('required_next_action', sa.String(length=300), nullable=False),
    sa.Column('review_required', sa.Boolean(), nullable=False),
    sa.Column('decision_payload', sa.JSON(), nullable=True),
    sa.Column('check_risk_level', sa.String(length=20), nullable=False),
    sa.Column('check_text', sa.Text(), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=120), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('pca_next_action', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('outcome_reason', sa.Text(), nullable=True),
    sa.Column('outcome_date', sa.Date(), nullable=True),
    sa.Column('outcome_product_name', sa.String(length=200), nullable=True),
    sa.Column('outcome_active_ingredient', sa.String(length=200), nullable=True),
    sa.Column('spray_event_id', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['pilot_import_batch_id'], ['pilot_import_batches.id'], ),
    sa.ForeignKeyConstraint(['spray_event_id'], ['spray_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planned_spray_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('system_recommendation', sa.String(length=30), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['planned_spray_id'], ['planned_sprays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_follow_up_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planned_spray_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('observed_at', sa.Date(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('severity_scale', sa.String(length=40), nullable=True),
    sa.Column('actual_product', sa.String(length=200), nullable=True),
    sa.Column('actual_rate_amount', sa.Float(), nullable=True),
    sa.Column('actual_rate_unit', sa.String(length=40), nullable=True),
    sa.Column('actual_treated_acres', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('rescue_required', sa.Boolean(), nullable=True),
    sa.Column('yield_impact', sa.String(length=20), nullable=True),
    sa.Column('quality_impact', sa.String(length=20), nullable=True),
    sa.Column('rejected_or_downgraded', sa.Boolean(), nullable=True),
    sa.Column('evidence_notes', sa.Text(), nullable=True),
    sa.Column('entered_by', sa.String(length=120), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['planned_spray_id'], ['planned_sprays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_input_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planned_spray_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=60), nullable=False),
    sa.Column('raw_value', sa.String(length=500), nullable=True),
    sa.Column('normalized_value', sa.String(length=500), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.String(length=40), nullable=True),
    sa.Column('verified_by', sa.String(length=120), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('supersedes_input_value_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['planned_spray_id'], ['planned_sprays.id'], ),
    sa.ForeignKeyConstraint(['supersedes_input_value_id'], ['decision_input_values.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('input_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_plan_id', sa.Integer(), nullable=False),
    sa.Column('planned_spray_id', sa.Integer(), nullable=True),
    sa.Column('field_block', sa.String(length=120), nullable=True),
    sa.Column('crop', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('active_ingredient', sa.String(length=200), nullable=True),
    sa.Column('moa_group', sa.String(length=40), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('acres', sa.Float(), nullable=True),
    sa.Column('needed_by_date', sa.Date(), nullable=False),
    sa.Column('intended_use', sa.String(length=200), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['input_plan_id'], ['input_plans.id'], ),
    sa.ForeignKeyConstraint(['planned_spray_id'], ['planned_sprays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('input_plan_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_input_plan_items_input_plan_id'), ['input_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_input_plan_items_planned_spray_id'), ['planned_spray_id'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('input_plan_id', sa.Integer(), nullable=False),
    sa.Column('selected_quote_id', sa.Integer(), nullable=False),
    sa.Column('accepted_financing_offer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('spray_event_id', sa.Integer(), nullable=True),
    sa.Column('applied_planned_spray_id', sa.Integer(), nullable=True),
    sa.Column('placed_by', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['accepted_financing_offer_id'], ['financing_offers.id'], ),
    sa.ForeignKeyConstraint(['applied_planned_spray_id'], ['planned_sprays.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['input_plan_id'], ['input_plans.id'], ),
    sa.ForeignKeyConstraint(['selected_quote_id'], ['supplier_quotes.id'], ),
    sa.ForeignKeyConstraint(['spray_event_id'], ['spray_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_input_plan_id'), ['input_plan_id'], unique=True)

    op.create_table('order_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_events_purchase_order_id'), ['purchase_order_id'], unique=False)

    op.create_table('supplier_quote_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_quote_id', sa.Integer(), nullable=False),
    sa.Column('input_plan_item_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('is_substitution', sa.Boolean(), nullable=False),
    sa.Column('substitution_reason', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['input_plan_item_id'], ['input_plan_items.id'], ),
    sa.ForeignKeyConstraint(['supplier_quote_id'], ['supplier_quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_quote_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_quote_items_input_plan_item_id'), ['input_plan_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_quote_items_supplier_quote_id'), ['supplier_quote_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_quote_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_quote_items_supplier_quote_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_quote_items_input_plan_item_id'))

    op.drop_table('supplier_quote_items')
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_events_purchase_order_id'))

    op.drop_table('order_events')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_input_plan_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_farm_id'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('input_plan_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_input_plan_items_planned_spray_id'))
        batch_op.drop_index(batch_op.f('ix_input_plan_items_input_plan_id'))

    op.drop_table('input_plan_items')
    op.drop_table('decision_input_values')
    op.drop_table('decision_follow_up_events')
    op.drop_table('decision_audit_events')
    op.drop_table('planned_sprays')
    with op.batch_alter_table('financing_offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financing_offers_supplier_quote_id'))

    op.drop_table('financing_offers')
    with op.batch_alter_table('supplier_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_quotes_input_plan_id'))

    op.drop_table('supplier_quotes')
    op.drop_table('spray_events')
    op.drop_table('scout_observations')
    with op.batch_alter_table('input_plan_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_input_plan_events_input_plan_id'))

    op.drop_table('input_plan_events')
    op.drop_table('spray_baselines')
    op.drop_table('recommendations')
    op.drop_table('pilot_import_batches')
    op.drop_table('pca_policies')
    with op.batch_alter_table('input_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_input_plans_farm_id'))

    op.drop_table('input_plans')
    op.drop_table('pilot_feedback')
    op.drop_table('pilot_events')
    op.drop_table('farms')
    op.drop_table('ai_judgments')
    # ### end Alembic commands ###
