"""add epa_reg_no to spray_events

Revision ID: 3328b685ac31
Revises: 86983fc42046
Create Date: 2026-07-26 11:42:39.157124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3328b685ac31'
down_revision: Union[str, Sequence[str], None] = '86983fc42046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spray_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('epa_reg_no', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spray_events', schema=None) as batch_op:
        batch_op.drop_column('epa_reg_no')

    # ### end Alembic commands ###
