"""opportunity scans and snapshot basis

Revision ID: 3c178a984c4c
Revises: cb6eacb389f0
Create Date: 2026-08-06 10:57:02.280409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c178a984c4c'
down_revision: Union[str, Sequence[str], None] = 'cb6eacb389f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('scan_version', sa.String(length=40), nullable=False),
    sa.Column('model_version', sa.String(length=60), nullable=False),
    sa.Column('target', sa.String(length=80), nullable=False),
    sa.Column('basis', sa.String(length=40), nullable=False),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('lookback_hours', sa.Integer(), nullable=False),
    sa.Column('dates_scanned', sa.Integer(), nullable=False),
    sa.Column('assessed_count', sa.Integer(), nullable=False),
    sa.Column('band_counts', sa.JSON(), nullable=True),
    sa.Column('reason_counts', sa.JSON(), nullable=True),
    sa.Column('grade_counts', sa.JSON(), nullable=True),
    sa.Column('run_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunity_scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunity_scans_basis'), ['basis'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_scans_block_id'), ['block_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_scans_farm_id'), ['farm_id'], unique=False)

    op.create_table('opportunity_scan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.Column('risk_band', sa.String(length=20), nullable=False),
    sa.Column('abstained', sa.Boolean(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.Column('evidence_grade', sa.String(length=2), nullable=True),
    sa.Column('probability_or_index', sa.Float(), nullable=True),
    sa.Column('input_digest', sa.String(length=64), nullable=False),
    sa.Column('excluded_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['opportunity_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunity_scan_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunity_scan_items_input_digest'), ['input_digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_scan_items_scan_id'), ['scan_id'], unique=False)

    with op.batch_alter_table('risk_input_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basis', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_risk_input_snapshots_basis'), ['basis'], unique=False)

    # Backfill AFTER the batch block: batch mode rebuilds the table on exit, so an
    # UPDATE issued inside it runs against the old table and fails on the missing column.
    #
    # This is a statement of fact rather than a convenience default. Every snapshot that
    # existed before this migration was built by the only code path that existed, which
    # admitted on BOTH timestamps. Leaving them NULL would make the strongest rows in
    # the table indistinguishable from rows of unknown basis.
    op.execute(
        "UPDATE risk_input_snapshots SET basis = 'point_in_time' WHERE basis IS NULL"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_input_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_input_snapshots_basis'))
        batch_op.drop_column('basis')

    with op.batch_alter_table('opportunity_scan_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunity_scan_items_scan_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_scan_items_input_digest'))

    op.drop_table('opportunity_scan_items')
    with op.batch_alter_table('opportunity_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunity_scans_farm_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_scans_block_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_scans_basis'))

    op.drop_table('opportunity_scans')
    # ### end Alembic commands ###
