"""residue reference records (USDA PDP)

Revision ID: 3e83278911f2
Revises: e5f5523df75d
Create Date: 2026-08-10 14:06:28.521378

Hand-written rather than autogenerated. The dev server was running with --reload while
`models.ResidueReferenceRecord` was added, so its `init_db()` had already created the
table via `create_all` and autogenerate correctly saw no diff against the live DB — the
desync ENGINEERING_GUIDELINES.md §8 warns about. The table is therefore created defensively here so a
FRESH database (which has never run create_all) gets it from the migration chain.

Unique on (pair + release digest) rather than on the pair alone: a corrected USDA
re-release of the same program year must be able to land alongside the original instead
of overwriting it. See models.ResidueReferenceRecord for the full reasoning.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e83278911f2'
down_revision: Union[str, Sequence[str], None] = 'e5f5523df75d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLE = "residue_reference_records"


def _exists(name: str) -> bool:
    bind = op.get_bind()
    return name in sa.inspect(bind).get_table_names()


def upgrade() -> None:
    """Upgrade schema."""
    if _exists(TABLE):
        # Already present from create_all on a dev database. Creating it again would
        # abort the upgrade with "table already exists" and block every later migration.
        return

    op.create_table(
        TABLE,
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("commodity_code", sa.String(length=4), nullable=False),
        sa.Column("commodity_name", sa.String(length=120), nullable=False),
        sa.Column("commodity_type", sa.String(length=4), nullable=False),
        sa.Column("pesticide_code", sa.String(length=8), nullable=False),
        sa.Column("pesticide_name", sa.String(length=160), nullable=False),
        sa.Column("program_year", sa.Integer(), nullable=False),
        sa.Column("samples_tested", sa.Integer(), nullable=False),
        sa.Column("samples_with_detection", sa.Integer(), nullable=False),
        # Nullable on purpose: NULL is "nothing was detected", not "detected at zero".
        sa.Column("max_concentration", sa.Float(), nullable=True),
        sa.Column("median_detected_concentration", sa.Float(), nullable=True),
        sa.Column("concentration_unit", sa.String(length=8), nullable=True),
        sa.Column("unit_conflict", sa.Boolean(), nullable=False),
        sa.Column("domestic_only", sa.Boolean(), nullable=False),
        # NULL means the source stated a non-numeric basis or nothing. Never "no limit".
        sa.Column("epa_tolerance_value", sa.Float(), nullable=True),
        sa.Column("epa_tolerance_basis", sa.String(length=4), nullable=True),
        sa.Column("tolerance_unit", sa.String(length=8), nullable=True),
        sa.Column("source_reference", sa.Text(), nullable=False),
        sa.Column("source_digest", sa.String(length=64), nullable=False),
        sa.Column("loaded_by", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_residue_reference_records")),
        sa.UniqueConstraint(
            "commodity_code", "commodity_type", "pesticide_code", "program_year",
            "domestic_only", "source_digest",
            name="uq_residue_reference_pair_release",
        ),
    )
    op.create_index(
        "ix_residue_reference_lookup", TABLE, ["commodity_code", "pesticide_code"],
    )
    op.create_index(
        op.f("ix_residue_reference_records_program_year"), TABLE, ["program_year"],
    )
    op.create_index(
        op.f("ix_residue_reference_records_source_digest"), TABLE, ["source_digest"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    if not _exists(TABLE):
        return
    op.drop_index(op.f("ix_residue_reference_records_source_digest"), table_name=TABLE)
    op.drop_index(op.f("ix_residue_reference_records_program_year"), table_name=TABLE)
    op.drop_index("ix_residue_reference_lookup", table_name=TABLE)
    op.drop_table(TABLE)
