"""sale records, block outcome cycle link, operation cost category

Revision ID: 3e9c7c860a81
Revises: 3e83278911f2
Create Date: 2026-08-12 11:12:13.800585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e9c7c860a81'
down_revision: Union[str, Sequence[str], None] = '3e83278911f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Three changes that make a crop cycle's economics computable:

    * `sale_records` — the revenue half of the season. Append-only in the application
      layer (a correction supersedes rather than edits), which is why `supersedes_id`
      is a self-referencing FK rather than the table carrying an `updated_at`.
    * `block_outcome_observations.crop_cycle_id` — nullable, so a harvest measured
      before the farm had a season stays honestly unattributed rather than being
      back-filled into a guess.
    * `operations.cost_category` — a lightweight grouping for the cost breakdown.

    EVERY foreign key is named explicitly. SQLite batch mode cannot create an unnamed
    constraint, and autogenerate emits `None` for both the create and the drop.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_cycle_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('gross_amount', sa.Float(), nullable=True),
    sa.Column('deductions_amount', sa.Float(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('buyer_name', sa.String(length=200), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('grade', sa.String(length=60), nullable=True),
    sa.Column('market', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('entered_by', sa.String(length=120), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(
        ['crop_cycle_id'], ['crop_cycles.id'], name='fk_sale_records_crop_cycle_id'
    ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name='fk_sale_records_farm_id'),
    sa.ForeignKeyConstraint(
        ['supersedes_id'], ['sale_records.id'], name='fk_sale_records_supersedes_id'
    ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_records_crop_cycle_id'), ['crop_cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_records_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_records_sale_date'), ['sale_date'], unique=False)

    with op.batch_alter_table('block_outcome_observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crop_cycle_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_block_outcome_observations_crop_cycle_id'), ['crop_cycle_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_block_outcome_observations_crop_cycle_id',
            'crop_cycles',
            ['crop_cycle_id'],
            ['id'],
        )

    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_category', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_operations_cost_category'), ['cost_category'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operations_cost_category'))
        batch_op.drop_column('cost_category')

    with op.batch_alter_table('block_outcome_observations', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_block_outcome_observations_crop_cycle_id', type_='foreignkey'
        )
        batch_op.drop_index(batch_op.f('ix_block_outcome_observations_crop_cycle_id'))
        batch_op.drop_column('crop_cycle_id')

    with op.batch_alter_table('sale_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_records_sale_date'))
        batch_op.drop_index(batch_op.f('ix_sale_records_farm_id'))
        batch_op.drop_index(batch_op.f('ix_sale_records_crop_cycle_id'))

    op.drop_table('sale_records')
    # ### end Alembic commands ###
