"""add pesticide products and label records

Revision ID: 46f2a212e88c
Revises: 3328b685ac31
Create Date: 2026-07-27 06:56:18.382514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46f2a212e88c'
down_revision: Union[str, Sequence[str], None] = '3328b685ac31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pesticide_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('epa_reg_no', sa.String(length=60), nullable=False),
    sa.Column('epa_reg_no_normalized', sa.String(length=60), nullable=False),
    sa.Column('epa_reg_base', sa.String(length=60), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('registrant', sa.String(length=200), nullable=True),
    sa.Column('active_ingredient', sa.String(length=200), nullable=True),
    sa.Column('active_ingredient_concentration_amount', sa.Float(), nullable=True),
    sa.Column('active_ingredient_concentration_unit', sa.String(length=40), nullable=True),
    sa.Column('moa_group', sa.String(length=40), nullable=True),
    sa.Column('registered_crops_transcription_complete', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pesticide_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pesticide_products_epa_reg_base'), ['epa_reg_base'], unique=False)
        batch_op.create_index(batch_op.f('ix_pesticide_products_epa_reg_no_normalized'), ['epa_reg_no_normalized'], unique=True)

    op.create_table('product_label_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('registered_crop', sa.String(length=120), nullable=False),
    sa.Column('registered_crop_normalized', sa.String(length=120), nullable=False),
    sa.Column('target_pest_or_disease', sa.String(length=200), nullable=True),
    sa.Column('pre_harvest_interval_days', sa.Integer(), nullable=True),
    sa.Column('re_entry_interval_hours', sa.Integer(), nullable=True),
    sa.Column('max_seasonal_rate_amount', sa.Float(), nullable=True),
    sa.Column('max_seasonal_rate_unit', sa.String(length=40), nullable=True),
    sa.Column('max_applications_per_season', sa.Integer(), nullable=True),
    sa.Column('min_retreatment_interval_days', sa.Integer(), nullable=True),
    sa.Column('label_version', sa.String(length=120), nullable=True),
    sa.Column('label_effective_date', sa.Date(), nullable=True),
    sa.Column('source_tier', sa.String(length=40), nullable=False),
    sa.Column('source_document_reference', sa.String(length=400), nullable=True),
    sa.Column('source_section_or_page', sa.String(length=200), nullable=True),
    sa.Column('source_snippet', sa.Text(), nullable=True),
    sa.Column('transcribed_by', sa.String(length=120), nullable=True),
    sa.Column('transcribed_at', sa.DateTime(), nullable=True),
    sa.Column('transcription_digest', sa.String(length=64), nullable=True),
    sa.Column('withdrawal_reason', sa.Text(), nullable=True),
    sa.Column('supersedes_label_record_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['pesticide_products.id'], ),
    sa.ForeignKeyConstraint(['supersedes_label_record_id'], ['product_label_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_label_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_label_records_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_label_records_supersedes_label_record_id'), ['supersedes_label_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_label_records_transcription_digest'), ['transcription_digest'], unique=False)

    op.create_table('product_label_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_label_record_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('verified_by_credential_id', sa.Integer(), nullable=False),
    sa.Column('verified_by', sa.String(length=120), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.Column('attestation', sa.Text(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['product_label_record_id'], ['product_label_records.id'], ),
    sa.ForeignKeyConstraint(['verified_by_credential_id'], ['pca_credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_label_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_label_verifications_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_label_verifications_product_label_record_id'), ['product_label_record_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_label_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_label_verifications_product_label_record_id'))
        batch_op.drop_index(batch_op.f('ix_product_label_verifications_farm_id'))

    op.drop_table('product_label_verifications')
    with op.batch_alter_table('product_label_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_label_records_transcription_digest'))
        batch_op.drop_index(batch_op.f('ix_product_label_records_supersedes_label_record_id'))
        batch_op.drop_index(batch_op.f('ix_product_label_records_product_id'))

    op.drop_table('product_label_records')
    with op.batch_alter_table('pesticide_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pesticide_products_epa_reg_no_normalized'))
        batch_op.drop_index(batch_op.f('ix_pesticide_products_epa_reg_base'))

    op.drop_table('pesticide_products')
    # ### end Alembic commands ###
