"""p1 ingestion runs and issues

Two tables and one column, so that outside data reaching the weather table is
auditable: `ingestion_runs` records what was asked for and what happened to it,
`ingestion_issues` records every row that was dropped and why, and
`weather_observations.ingestion_run_id` links a reading back to the run that wrote it.

The link is a nullable FK rather than a string in `source_reference` because the audit
question is "what else did that run write, and what did it drop" — which a free-text
field cannot answer. It is also deliberately absent from
`risk_snapshot._weather_payload`, so adding it leaves every stored snapshot digest
byte-identical.

No unique constraint on `ingestion_runs`: idempotency is enforced upstream by the job
queue's live idempotency key and downstream by the partial unique index on
`weather_observations`, both of which are stronger than a constraint here would be.

Revision ID: 48dabb5f1b34
Revises: 9c591048c3b2
Create Date: 2026-08-05 17:44:10.131411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48dabb5f1b34'
down_revision: Union[str, Sequence[str], None] = '9c591048c3b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=80), nullable=False),
    sa.Column('domain', sa.String(length=40), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('window_start', sa.DateTime(), nullable=True),
    sa.Column('window_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('adapter_version', sa.String(length=20), nullable=True),
    sa.Column('request_digest', sa.String(length=64), nullable=True),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('parsed_count', sa.Integer(), nullable=False),
    sa.Column('admitted_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('superseded_count', sa.Integer(), nullable=False),
    sa.Column('issue_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestion_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_runs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_runs_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_runs_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_runs_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_runs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_runs_source_key'), ['source_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_runs_status'), ['status'], unique=False)

    op.create_table('ingestion_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('natural_key', sa.String(length=200), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestion_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_issues_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_issues_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_issues_stage'), ['stage'], unique=False)

    with op.batch_alter_table('weather_observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingestion_run_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_weather_observations_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        # NAMED on purpose: SQLite batch mode rebuilds the table to drop a constraint,
        # and it cannot drop one it cannot name. An autogenerated `None` here passes
        # upgrade and fails downgrade, which is the worst place to find out.
        batch_op.create_foreign_key(
            'fk_weather_observations_ingestion_run_id',
            'ingestion_runs', ['ingestion_run_id'], ['id'],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_observations', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_weather_observations_ingestion_run_id', type_='foreignkey'
        )
        batch_op.drop_index(batch_op.f('ix_weather_observations_ingestion_run_id'))
        batch_op.drop_column('ingestion_run_id')

    with op.batch_alter_table('ingestion_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_issues_stage'))
        batch_op.drop_index(batch_op.f('ix_ingestion_issues_ingestion_run_id'))
        batch_op.drop_index(batch_op.f('ix_ingestion_issues_code'))

    op.drop_table('ingestion_issues')
    with op.batch_alter_table('ingestion_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_runs_status'))
        batch_op.drop_index(batch_op.f('ix_ingestion_runs_source_key'))
        batch_op.drop_index(batch_op.f('ix_ingestion_runs_job_id'))
        batch_op.drop_index(batch_op.f('ix_ingestion_runs_field_id'))
        batch_op.drop_index(batch_op.f('ix_ingestion_runs_farm_id'))
        batch_op.drop_index(batch_op.f('ix_ingestion_runs_domain'))
        batch_op.drop_index(batch_op.f('ix_ingestion_runs_document_id'))

    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
