"""add disease risk assessments

Revision ID: 531268cb209a
Revises: 915bf6e2e309
Create Date: 2026-07-20 12:29:21.119967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '531268cb209a'
down_revision: Union[str, Sequence[str], None] = '915bf6e2e309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease_risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('planned_spray_id', sa.Integer(), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('model_family', sa.String(length=60), nullable=False),
    sa.Column('model_version', sa.String(length=60), nullable=False),
    sa.Column('input_digest', sa.String(length=64), nullable=False),
    sa.Column('risk_band', sa.String(length=20), nullable=False),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('evidence_grade', sa.String(length=2), nullable=True),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('abstained', sa.Boolean(), nullable=False),
    sa.Column('abstain_reason', sa.String(length=80), nullable=True),
    sa.Column('missing_inputs', sa.JSON(), nullable=True),
    sa.Column('calibration_status', sa.String(length=40), nullable=False),
    sa.Column('local_validation_status', sa.Text(), nullable=True),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.Column('calculation', sa.JSON(), nullable=True),
    sa.Column('is_shadow', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('data_source', sa.String(length=40), nullable=False),
    sa.Column('data_confidence', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['planned_spray_id'], ['planned_sprays.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['risk_input_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disease_risk_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disease_risk_assessments_block_id'), ['block_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disease_risk_assessments_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disease_risk_assessments_input_digest'), ['input_digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_disease_risk_assessments_planned_spray_id'), ['planned_spray_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disease_risk_assessments_snapshot_id'), ['snapshot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disease_risk_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disease_risk_assessments_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_disease_risk_assessments_planned_spray_id'))
        batch_op.drop_index(batch_op.f('ix_disease_risk_assessments_input_digest'))
        batch_op.drop_index(batch_op.f('ix_disease_risk_assessments_farm_id'))
        batch_op.drop_index(batch_op.f('ix_disease_risk_assessments_block_id'))

    op.drop_table('disease_risk_assessments')
    # ### end Alembic commands ###
