"""add risk input snapshots

Revision ID: 82eb1798a291
Revises: 910eff0634e0
Create Date: 2026-07-19 19:39:04.444188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82eb1798a291'
down_revision: Union[str, Sequence[str], None] = '910eff0634e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_input_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('planned_spray_id', sa.Integer(), nullable=True),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=80), nullable=False),
    sa.Column('snapshot_version', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('input_digest', sa.String(length=64), nullable=False),
    sa.Column('excluded', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['planned_spray_id'], ['planned_sprays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_input_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_input_snapshots_block_id'), ['block_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_input_snapshots_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_input_snapshots_input_digest'), ['input_digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_input_snapshots_planned_spray_id'), ['planned_spray_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_input_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_input_snapshots_planned_spray_id'))
        batch_op.drop_index(batch_op.f('ix_risk_input_snapshots_input_digest'))
        batch_op.drop_index(batch_op.f('ix_risk_input_snapshots_farm_id'))
        batch_op.drop_index(batch_op.f('ix_risk_input_snapshots_block_id'))

    op.drop_table('risk_input_snapshots')
    # ### end Alembic commands ###
