"""add pilot protocol assignments and block outcomes

Revision ID: 86983fc42046
Revises: b0fc6b5fd6d2
Create Date: 2026-07-20 12:42:44.676407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86983fc42046'
down_revision: Union[str, Sequence[str], None] = 'b0fc6b5fd6d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pilot_protocols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('document_reference', sa.Text(), nullable=True),
    sa.Column('assignment_method', sa.String(length=20), nullable=False),
    sa.Column('target', sa.String(length=80), nullable=False),
    sa.Column('primary_metric', sa.String(length=120), nullable=False),
    sa.Column('secondary_metrics', sa.JSON(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('unblinded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('data_source', sa.String(length=40), nullable=False),
    sa.Column('data_confidence', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pilot_protocols', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pilot_protocols_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index('uq_pilot_protocol_active_version', ['farm_id', 'version'], unique=True, sqlite_where=sa.text('effective_to IS NULL'))

    op.create_table('block_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pilot_protocol_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('arm', sa.String(length=20), nullable=False),
    sa.Column('matched_pair_key', sa.String(length=60), nullable=True),
    sa.Column('assigned_on', sa.Date(), nullable=False),
    sa.Column('assigned_by', sa.String(length=120), nullable=True),
    sa.Column('assignment_seed', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('data_source', sa.String(length=40), nullable=False),
    sa.Column('data_confidence', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['pilot_protocol_id'], ['pilot_protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('block_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_block_assignments_block_id'), ['block_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_block_assignments_matched_pair_key'), ['matched_pair_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_block_assignments_pilot_protocol_id'), ['pilot_protocol_id'], unique=False)
        batch_op.create_index('uq_block_assignment_per_protocol', ['pilot_protocol_id', 'block_id'], unique=True)

    op.create_table('block_outcome_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('pilot_protocol_id', sa.Integer(), nullable=True),
    sa.Column('observed_on', sa.Date(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('outcome_type', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('denominator', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=True),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('data_source', sa.String(length=40), nullable=False),
    sa.Column('data_confidence', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['pilot_protocol_id'], ['pilot_protocols.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['block_outcome_observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('block_outcome_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_block_outcome_observations_block_id'), ['block_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_block_outcome_observations_pilot_protocol_id'), ['pilot_protocol_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_outcome_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_block_outcome_observations_pilot_protocol_id'))
        batch_op.drop_index(batch_op.f('ix_block_outcome_observations_block_id'))

    op.drop_table('block_outcome_observations')
    with op.batch_alter_table('block_assignments', schema=None) as batch_op:
        batch_op.drop_index('uq_block_assignment_per_protocol')
        batch_op.drop_index(batch_op.f('ix_block_assignments_pilot_protocol_id'))
        batch_op.drop_index(batch_op.f('ix_block_assignments_matched_pair_key'))
        batch_op.drop_index(batch_op.f('ix_block_assignments_block_id'))

    op.drop_table('block_assignments')
    with op.batch_alter_table('pilot_protocols', schema=None) as batch_op:
        batch_op.drop_index('uq_pilot_protocol_active_version', sqlite_where=sa.text('effective_to IS NULL'))
        batch_op.drop_index(batch_op.f('ix_pilot_protocols_farm_id'))

    op.drop_table('pilot_protocols')
    # ### end Alembic commands ###
