"""add treated_area_unit to sprays and planned sprays

Revision ID: 915bf6e2e309
Revises: 82eb1798a291
Create Date: 2026-07-20 12:19:10.149088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '915bf6e2e309'
down_revision: Union[str, Sequence[str], None] = '82eb1798a291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('planned_sprays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treated_area_unit', sa.String(length=10), nullable=True))

    with op.batch_alter_table('spray_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treated_area_unit', sa.String(length=10), nullable=True))

    # Backfill from the farm's declared area unit. This is a LOOKUP, not a conversion:
    # the stored numbers are untouched, we only record what they were always in.
    # Rows with no treated area stay NULL, and so do rows on a farm that never
    # declared an area unit — unspecified is honest, "acres" would be a guess.
    for table in ("planned_sprays", "spray_events"):
        op.execute(
            f"UPDATE {table} SET treated_area_unit = ("
            f"  SELECT farms.area_unit FROM farms WHERE farms.id = {table}.farm_id"
            f") WHERE treated_acres IS NOT NULL"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spray_events', schema=None) as batch_op:
        batch_op.drop_column('treated_area_unit')

    with op.batch_alter_table('planned_sprays', schema=None) as batch_op:
        batch_op.drop_column('treated_area_unit')

    # ### end Alembic commands ###
