"""add pca dispositions

Revision ID: b0fc6b5fd6d2
Revises: 531268cb209a
Create Date: 2026-07-20 12:36:07.458361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0fc6b5fd6d2'
down_revision: Union[str, Sequence[str], None] = '531268cb209a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pca_dispositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planned_spray_id', sa.Integer(), nullable=False),
    sa.Column('pca_credential_id', sa.Integer(), nullable=False),
    sa.Column('disposition', sa.String(length=40), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_digest_at_decision', sa.String(length=64), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=False),
    sa.Column('data_confidence', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['disease_risk_assessments.id'], ),
    sa.ForeignKeyConstraint(['pca_credential_id'], ['pca_credentials.id'], ),
    sa.ForeignKeyConstraint(['planned_spray_id'], ['planned_sprays.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['pca_dispositions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pca_dispositions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pca_dispositions_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pca_dispositions_pca_credential_id'), ['pca_credential_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pca_dispositions_planned_spray_id'), ['planned_spray_id'], unique=False)
        batch_op.create_index('uq_pca_disposition_live_per_decision', ['planned_spray_id'], unique=True, sqlite_where=sa.text('supersedes_id IS NULL'), postgresql_where=sa.text('supersedes_id IS NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pca_dispositions', schema=None) as batch_op:
        batch_op.drop_index('uq_pca_disposition_live_per_decision', sqlite_where=sa.text('supersedes_id IS NULL'), postgresql_where=sa.text('supersedes_id IS NULL'))
        batch_op.drop_index(batch_op.f('ix_pca_dispositions_planned_spray_id'))
        batch_op.drop_index(batch_op.f('ix_pca_dispositions_pca_credential_id'))
        batch_op.drop_index(batch_op.f('ix_pca_dispositions_assessment_id'))

    op.drop_table('pca_dispositions')
    # ### end Alembic commands ###
