"""p0_documents_and_job_queue

Revision ID: c992ddc1abfa
Revises: 3fc3f253cc02
Create Date: 2026-07-28 18:06:02.264330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c992ddc1abfa'
down_revision: Union[str, Sequence[str], None] = '3fc3f253cc02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queue', sa.String(length=40), nullable=False),
    sa.Column('task_name', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=80), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('locked_by', sa.String(length=120), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_job_claimable', ['status', 'run_at', 'priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_queue'), ['queue'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_source_key'), ['source_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_task_name'), ['task_name'], unique=False)
        batch_op.create_index('uq_job_live_idempotency_key', ['idempotency_key'], unique=True, sqlite_where=sa.text("status IN ('pending', 'running')"), postgresql_where=sa.text("status IN ('pending', 'running')"))

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('subject_type', sa.String(length=60), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_storage_key'), ['storage_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_subject_type'), ['subject_type'], unique=False)

    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=120), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_runs_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_runs_job_id'))

    op.drop_table('job_runs')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_subject_type'))
        batch_op.drop_index(batch_op.f('ix_documents_subject_id'))
        batch_op.drop_index(batch_op.f('ix_documents_storage_key'))
        batch_op.drop_index(batch_op.f('ix_documents_sha256'))
        batch_op.drop_index(batch_op.f('ix_documents_kind'))
        batch_op.drop_index(batch_op.f('ix_documents_farm_id'))

    op.drop_table('documents')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('uq_job_live_idempotency_key', sqlite_where=sa.text("status IN ('pending', 'running')"), postgresql_where=sa.text("status IN ('pending', 'running')"))
        batch_op.drop_index(batch_op.f('ix_jobs_task_name'))
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_source_key'))
        batch_op.drop_index(batch_op.f('ix_jobs_queue'))
        batch_op.drop_index('ix_job_claimable')

    op.drop_table('jobs')
    # ### end Alembic commands ###
