"""p1 feature values

Stored derived values, one per (entity, feature, version, as_of).

The unique constraint is FULL, not partial, and there is no supersede chain — a
deliberate difference from every observation table in this schema. It follows from
point-in-time correctness: since `pit.admissible` excludes anything recorded after
`as_of`, recomputing at a FIXED `as_of` must reproduce the identical `inputs_digest`
forever, however much data has arrived since. There is therefore nothing to supersede.

Which makes this table a leak detector. A digest that moves at an unchanged `as_of` is
proof that an input became visible which should not have been, so `compute.persist`
leaves the stored row alone and records the disagreement rather than overwriting it.

An abstention is a row with `value IS NULL` and non-empty `reasons`. The pair is
enforced upstream in `features.base.FeatureResult`, so no row here can claim to have no
value and no reason at once.

Revision ID: cb6eacb389f0
Revises: 48dabb5f1b34
Create Date: 2026-08-05 18:21:38.446845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb6eacb389f0'
down_revision: Union[str, Sequence[str], None] = '48dabb5f1b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('evidence_grade', sa.String(length=10), nullable=True),
    sa.Column('abstained', sa.Boolean(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.Column('excluded', sa.JSON(), nullable=True),
    sa.Column('inputs_digest', sa.String(length=64), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'name', 'version', 'as_of', name='uq_feature_value_entity_name_version_as_of')
    )
    with op.batch_alter_table('feature_values', schema=None) as batch_op:
        batch_op.create_index('ix_feature_value_lookup', ['entity_type', 'entity_id', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_values_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_values_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_values_name'))
        batch_op.drop_index(batch_op.f('ix_feature_values_farm_id'))
        batch_op.drop_index('ix_feature_value_lookup')

    op.drop_table('feature_values')
    # ### end Alembic commands ###
