"""marketplace: suppliers, catalog links, rfq transmissions

Revision ID: d1e4e7de3145
Revises: 3c178a984c4c
Create Date: 2026-08-07 14:17:55.695236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e4e7de3145'
down_revision: Union[str, Sequence[str], None] = '3c178a984c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=60), nullable=True),
    sa.Column('service_area', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_canonical_name'), ['canonical_name'], unique=False)

    op.create_table('supplier_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('input_product_id', sa.Integer(), nullable=False),
    sa.Column('supplier_sku', sa.String(length=120), nullable=True),
    sa.Column('pack_size', sa.String(length=60), nullable=True),
    sa.Column('typical_lead_time_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['input_product_id'], ['input_products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_products_input_product_id'), ['input_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_products_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index('uq_supplier_product', ['supplier_id', 'input_product_id'], unique=True)

    op.create_table('rfq_transmissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_plan_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('sent_to', sa.String(length=200), nullable=True),
    sa.Column('transport', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['input_plan_id'], ['input_plans.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rfq_transmissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rfq_transmissions_input_plan_id'), ['input_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rfq_transmissions_supplier_id'), ['supplier_id'], unique=False)

    with op.batch_alter_table('supplier_quote_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_product_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_supplier_quote_items_input_product_id'), ['input_product_id'], unique=False)
        # Named explicitly: SQLite batch mode cannot create an unnamed constraint,
        # and an autogenerated `None` here fails with "Constraint must have a name".
        batch_op.create_foreign_key(
            'fk_supplier_quote_items_input_product', 'input_products',
            ['input_product_id'], ['id'],
        )

    with op.batch_alter_table('supplier_quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_supplier_quotes_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_supplier_quotes_supplier', 'suppliers', ['supplier_id'], ['id'],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_quotes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_supplier_quotes_supplier', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_supplier_quotes_supplier_id'))
        batch_op.drop_column('supplier_id')

    with op.batch_alter_table('supplier_quote_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_supplier_quote_items_input_product', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_supplier_quote_items_input_product_id'))
        batch_op.drop_column('input_product_id')

    with op.batch_alter_table('rfq_transmissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rfq_transmissions_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_rfq_transmissions_input_plan_id'))

    op.drop_table('rfq_transmissions')
    with op.batch_alter_table('supplier_products', schema=None) as batch_op:
        batch_op.drop_index('uq_supplier_product')
        batch_op.drop_index(batch_op.f('ix_supplier_products_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_products_input_product_id'))

    op.drop_table('supplier_products')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_canonical_name'))

    op.drop_table('suppliers')
    # ### end Alembic commands ###
