"""finance persistence tables

Revision ID: e5f5523df75d
Revises: d1e4e7de3145
Create Date: 2026-08-07 16:43:55.031281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f5523df75d'
down_revision: Union[str, Sequence[str], None] = 'd1e4e7de3145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coverage_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.Column('crop', sa.String(length=80), nullable=True),
    sa.Column('peril', sa.String(length=80), nullable=True),
    sa.Column('products', sa.JSON(), nullable=True),
    sa.Column('refusal_code', sa.String(length=60), nullable=True),
    sa.Column('refusal_detail', sa.Text(), nullable=True),
    sa.Column('assessed_by', sa.String(length=120), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coverage_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coverage_assessments_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_coverage_assessments_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coverage_assessments_refusal_code'), ['refusal_code'], unique=False)

    op.create_table('credit_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.Column('scorecard_lender', sa.String(length=200), nullable=True),
    sa.Column('scorecard_name', sa.String(length=200), nullable=True),
    sa.Column('scorecard_version', sa.String(length=60), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('minimum_score', sa.Float(), nullable=True),
    sa.Column('maximum_score', sa.Float(), nullable=True),
    sa.Column('inputs_digest', sa.String(length=64), nullable=True),
    sa.Column('factors', sa.JSON(), nullable=True),
    sa.Column('refusal_code', sa.String(length=60), nullable=True),
    sa.Column('refusal_detail', sa.Text(), nullable=True),
    sa.Column('assessed_by', sa.String(length=120), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_assessments_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_assessments_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_assessments_inputs_digest'), ['inputs_digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_assessments_refusal_code'), ['refusal_code'], unique=False)

    op.create_table('monitoring_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.Column('lender', sa.String(length=200), nullable=True),
    sa.Column('facility_reference', sa.String(length=120), nullable=True),
    sa.Column('standing', sa.String(length=40), nullable=True),
    sa.Column('covenants', sa.JSON(), nullable=True),
    sa.Column('breached_covenant_ids', sa.JSON(), nullable=True),
    sa.Column('unevaluated_covenant_ids', sa.JSON(), nullable=True),
    sa.Column('refusal_code', sa.String(length=60), nullable=True),
    sa.Column('refusal_detail', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_snapshots_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_snapshots_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_snapshots_refusal_code'), ['refusal_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_snapshots_standing'), ['standing'], unique=False)

    op.create_table('collateral_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('collateral_type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assessed_value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('valuation_basis', sa.String(length=200), nullable=True),
    sa.Column('valued_on', sa.Date(), nullable=True),
    sa.Column('land_parcel_id', sa.Integer(), nullable=True),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('registered_by', sa.String(length=120), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['land_parcel_id'], ['land_parcels.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['collateral_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collateral_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collateral_assets_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collateral_assets_land_parcel_id'), ['land_parcel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collateral_assets_supersedes_id'), ['supersedes_id'], unique=False)

    op.create_table('underwriting_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.Column('credit_assessment_id', sa.Integer(), nullable=True),
    sa.Column('policy_lender', sa.String(length=200), nullable=True),
    sa.Column('policy_version', sa.String(length=60), nullable=True),
    sa.Column('outcome', sa.String(length=40), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('failed_rule_ids', sa.JSON(), nullable=True),
    sa.Column('not_evaluated_rule_ids', sa.JSON(), nullable=True),
    sa.Column('refusal_code', sa.String(length=60), nullable=True),
    sa.Column('refusal_detail', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(length=120), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['credit_assessment_id'], ['credit_assessments.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('underwriting_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_underwriting_decisions_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_underwriting_decisions_credit_assessment_id'), ['credit_assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_underwriting_decisions_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_underwriting_decisions_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_underwriting_decisions_refusal_code'), ['refusal_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('underwriting_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_underwriting_decisions_refusal_code'))
        batch_op.drop_index(batch_op.f('ix_underwriting_decisions_outcome'))
        batch_op.drop_index(batch_op.f('ix_underwriting_decisions_farm_id'))
        batch_op.drop_index(batch_op.f('ix_underwriting_decisions_credit_assessment_id'))
        batch_op.drop_index(batch_op.f('ix_underwriting_decisions_as_of'))

    op.drop_table('underwriting_decisions')
    with op.batch_alter_table('collateral_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collateral_assets_supersedes_id'))
        batch_op.drop_index(batch_op.f('ix_collateral_assets_land_parcel_id'))
        batch_op.drop_index(batch_op.f('ix_collateral_assets_farm_id'))

    op.drop_table('collateral_assets')
    with op.batch_alter_table('monitoring_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_snapshots_standing'))
        batch_op.drop_index(batch_op.f('ix_monitoring_snapshots_refusal_code'))
        batch_op.drop_index(batch_op.f('ix_monitoring_snapshots_farm_id'))
        batch_op.drop_index(batch_op.f('ix_monitoring_snapshots_as_of'))

    op.drop_table('monitoring_snapshots')
    with op.batch_alter_table('credit_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_assessments_refusal_code'))
        batch_op.drop_index(batch_op.f('ix_credit_assessments_inputs_digest'))
        batch_op.drop_index(batch_op.f('ix_credit_assessments_farm_id'))
        batch_op.drop_index(batch_op.f('ix_credit_assessments_as_of'))

    op.drop_table('credit_assessments')
    with op.batch_alter_table('coverage_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coverage_assessments_refusal_code'))
        batch_op.drop_index(batch_op.f('ix_coverage_assessments_farm_id'))
        batch_op.drop_index(batch_op.f('ix_coverage_assessments_as_of'))

    op.drop_table('coverage_assessments')
    # ### end Alembic commands ###
