"""farm intelligence: season financing, lender policies, commercial agreements

Revision ID: f356b91d9d1f
Revises: 3e9c7c860a81
Create Date: 2026-08-12 16:02:51.695324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f356b91d9d1f'
down_revision: Union[str, Sequence[str], None] = '3e9c7c860a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lender_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lender', sa.String(length=200), nullable=False),
    sa.Column('policy_version', sa.String(length=60), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('source_document', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('covenants', sa.JSON(), nullable=True),
    sa.Column('entered_by', sa.String(length=120), nullable=True),
    sa.Column('entered_on', sa.Date(), nullable=True),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supersedes_id'], ['lender_policies.id'], name='fk_lender_policies_supersedes_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lender_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lender_policies_lender'), ['lender'], unique=False)
        batch_op.create_index(batch_op.f('ix_lender_policies_supersedes_id'), ['supersedes_id'], unique=False)

    op.create_table('commercial_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('model_type', sa.String(length=40), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('terms', sa.JSON(), nullable=True),
    sa.Column('source_document', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('entered_by', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['commercial_agreements.id'], name='fk_commercial_agreements_supersedes_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commercial_agreements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commercial_agreements_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commercial_agreements_supersedes_id'), ['supersedes_id'], unique=False)

    op.create_table('financing_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('crop_cycle_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('requested_amount', sa.Float(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('lender_policy_id', sa.Integer(), nullable=True),
    sa.Column('requested_by', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['lender_policy_id'], ['lender_policies.id'], name='fk_financing_requests_lender_policy_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financing_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financing_requests_crop_cycle_id'), ['crop_cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financing_requests_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financing_requests_lender_policy_id'), ['lender_policy_id'], unique=False)

    op.create_table('financing_request_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financing_request_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['financing_request_id'], ['financing_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financing_request_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financing_request_events_financing_request_id'), ['financing_request_id'], unique=False)

    with op.batch_alter_table('financing_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('financing_request_id', sa.Integer(), nullable=True))
        batch_op.alter_column('supplier_quote_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_financing_offers_financing_request_id'), ['financing_request_id'], unique=False)
        batch_op.create_foreign_key('fk_financing_offers_request_id', 'financing_requests', ['financing_request_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financing_offers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_financing_offers_request_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_financing_offers_financing_request_id'))
        batch_op.alter_column('supplier_quote_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('financing_request_id')

    with op.batch_alter_table('financing_request_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financing_request_events_financing_request_id'))

    op.drop_table('financing_request_events')
    with op.batch_alter_table('financing_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financing_requests_lender_policy_id'))
        batch_op.drop_index(batch_op.f('ix_financing_requests_farm_id'))
        batch_op.drop_index(batch_op.f('ix_financing_requests_crop_cycle_id'))

    op.drop_table('financing_requests')
    with op.batch_alter_table('commercial_agreements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commercial_agreements_supersedes_id'))
        batch_op.drop_index(batch_op.f('ix_commercial_agreements_farm_id'))

    op.drop_table('commercial_agreements')
    with op.batch_alter_table('lender_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lender_policies_supersedes_id'))
        batch_op.drop_index(batch_op.f('ix_lender_policies_lender'))

    op.drop_table('lender_policies')
    # ### end Alembic commands ###
